git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }
source 'https://rubygems.org'

ruby '~> 3.1.4'

gem 'aws-sdk-s3', '~> 1.30'
gem 'dotenv'
gem 'hashie'
gem 'mocha'
gem 'rexml'
gem 'ruby-saml', '>= 1.9.0'
gem 'rack-test', '>= 2.0.0'
gem 'rake'
gem 'sinatra', '>= 3.0.4'
gem 'sinatra-contrib'
gem 'htmlbeautifier'
gem 'test-unit'
gem 'activesupport'
gem 'puma', '~> 6.4.2'

group :development do
  gem 'pry'
end
